"""initial schema

Revision ID: c886578febd6
Revises: 
Create Date: 2026-04-02 15:49:20.014020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c886578febd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_team', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_league_team_user_id'), 'league_team', ['user_id'], unique=False)
    op.create_foreign_key(None, 'league_team', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_team', type_='foreignkey')
    op.drop_index(op.f('ix_league_team_user_id'), table_name='league_team')
    op.drop_column('league_team', 'user_id')
    # ### end Alembic commands ###
